### ISSUE TITLE
Add more support for IPv6

### ISSUE THREAD

**Issue by haraldkoch** [onedr0p/cluster-template#1148]
Long time user, first time caller.

I think there are some templating modifications that could be made to add more IPv6 support.

**Comment by onedr0p** [comment]
I think this is blocked by Cilium: https://docs.cilium.io/en/latest/network/l2-announcements/

> Since this feature has no IPv6 support yet, only ARP messages are sent, no Unsolicited Neighbor Advertisements are sent.

Ref: https://github.com/cilium/cilium/issues/28985
