### ISSUE TITLE
Change jinja block delimiters

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/cluster-template#1175]
PR was merged to ignore these blocks in YAML but we need to wait for a release, and for the renovate app to be updated to it. Waiting on renovate `37.137.3`

https://github.com/renovatebot/renovate/pull/26682

https://developer.mend.io/github/onedr0p/flux-cluster-template/ is currently on `37.153.2`

**Comment by prehor** [comment]
[Renovate 37.137.3](/renovatebot/renovate/releases/tag/37.137.3)  includes your renovatebot/renovate/pull/26682

**Comment by onedr0p** [comment]
Yep! I am just waiting for their hosted renovate platform to update to it.

**Comment by onedr0p** [comment]
I went ahead and made these changes even though the renovate is not updated to the version needed. Once it is updated updates should start to roll in for templates with the jinja delimiters

**Comment by onedr0p** [comment]
Judging by the logs it doesn't look like Renovate can still properly handle these delimiters.
