### ISSUE TITLE
Support talos system extensions

### ISSUE THREAD

**Issue by mrueg** [onedr0p/cluster-template#1248]
This might be the opposite of your effort in https://github.com/onedr0p/flux-cluster-template/pull/1247
It would be nice to support talos system [extensions](https://github.com/siderolabs/extensions) in some shape or form.
(In particular interested in https://github.com/siderolabs/extensions/tree/main/network/tailscale )

I think a way to extend the talos config with a custom config would be nice.

**Comment by buroa** [comment]
@mrueg Is there a good reason to use the extension over just doing [this](https://github.com/buroa/k8s-gitops/tree/master/kubernetes/apps/networking/tailscale)?

**Comment by mrueg** [comment]
@buroa my hope was to expose the kube api via tailscale as well (I haven't looked into the extension yet, if it's possible). So I wanted to keep it outside of the cluster.

**Comment by buroa** [comment]
@mrueg You can do that just fine deploying it like I do. Nothing is special about the Talos extension way, it's just a bit weird.

**Comment by onedr0p** [comment]
@mrueg I merged that PR, hopefully this covers your use-case.

**Comment by mrueg** [comment]
thanks a lot!
