### ISSUE TITLE
Networking with cilium 1.15.0 does not work

### ISSUE THREAD

**Issue by prehor** [onedr0p/cluster-template#1295]
I created a fresh repository from the `cluster-template`, filled in the `config.yaml` and deployed the k3s single-node cluster on Debian 12. Flux was unable to start:
```bash
# task kubernetes:resources
task: [kubernetes:resources] kubectl get nodes -A
NAME   STATUS   ROLES                       AGE   VERSION
h1     Ready    control-plane,etcd,master   22m   v1.29.1+k3s1
task: [kubernetes:resources] kubectl get gitrepositories -A
NAMESPACE     NAME              URL                                  AGE   READY   STATUS
flux-system   home-kubernetes   https://github.com/prehor/home-ops   92s   False   failed to checkout and determine revision: unable to clone 'https://github.com/prehor/home-ops': Get "https://github.com/prehor/home-ops/info/refs?service=git-upload-pack": dial tcp: lookup github.com on 10.96.0.10:53: server misbehaving
```
I started busybox in the cluster and found out that the container is not able to network communicate outside its subnet and therefore cannot even make DNS queries to the IP address of the DNS service in the cluster services subnet.

I looked for the cause of the problem and found that if I revert #1280 and return the cilium version to 1.14.6, the cluster is functional, the containers have access even outside their own subnet, and Flux works.

**Comment by onedr0p** [comment]
That's really weird because I've tested on some of my hardware and even running 1.15.0 in my main and storage clusters just fine.

**Comment by onedr0p** [comment]
Thanks for investigating this. Glad you got it sorted.
