### ISSUE TITLE
Talos config assumes gateway is on .1 address

### ISSUE THREAD

**Issue by wouterbouvy** [onedr0p/cluster-template#1311]
Had to do some debugging on this one.... Looking at:
https://github.com/onedr0p/cluster-template/raw/main/bootstrap/templates/kubernetes/talos/talconfig.yaml.j2
```
        routes:
          - network: 0.0.0.0/0
            gateway: "{{ nodes.host_network | nthhost(1) }}"
``` 
Assumes the gateway is on the .1 of the CIDR, which in my case is on .254.
Would maybe be nicer to put this as variable in the `config.yaml`?

**Comment by onedr0p** [comment]
Interesting... mostly everywhere I look the default gateway on subnets is set to `.1`

**Comment by wouterbouvy** [comment]
I also use the .1 as the gateway on most of my VLANs/subnets. But ironically on my k8s VLANs I like the esthetic of having my nodes on the .1-.6 range.

It's just that your code isn't universally applicable to everyone.

**Comment by onedr0p** [comment]
My nodes are .10 thru .15, I honestly never considered changing the default gateway as it's really common that's on .1

> It's just that your code isn't universally applicable to everyone.

Yeah I get that but I'm trying to keep the configuration light as I can to make maintenance easier and less options people need to read over when they go to use this project.

**Comment by wouterbouvy** [comment]
Whatever you prefer. You can close this issue or I can draft a PR to add it as an optional config item. There are also options for VLAN and BGP in there, which are edge as well IMHO.

**Comment by onedr0p** [comment]
I am fine with a PR if you want to add an option to set the default gateway IP, I would just make sure to update all the references where `nthhost` is used.
