### ISSUE TITLE
Talos secrets file is ignored due to incorrect name

### ISSUE THREAD

**Issue by bluevulpine** [onedr0p/cluster-template#1358]
After standing up a Talos cluster, I wanted to edit the sysctls on some of the nodes, so I edited the talhelper config and allowed it to regenerate the node configurations and the talosconfig. I immediately lost access to the cluster due to a certificate mismatch error - the CA was no longer a valid match, which told me new secrets had been generated in place of the old ones.

Running `talhelper genconfig -d` reveals that it generated new ones and isn't actually using the talhelper.sops.yaml secrets file because the secret file was not found: 

```
❯ ls -l
total 40
drwxr-xr-x   5 bluevulpine  staff   160 Feb 29 18:51 apps
drwx------  13 bluevulpine  staff   416 Mar  6 23:35 clusterconfig
-rw-r--r--   1 bluevulpine  staff  7318 Mar  6 23:50 talconfig.yaml
-rw-r--r--   1 bluevulpine  staff  8914 Feb 29 18:52 talhelper.sops.yaml

❯ talhelper --version
talhelper version 2.3.3

❯ talhelper genconfig -d
2024/03/07 09:11:13 DEBUG start loading and validating config file
2024/03/07 09:11:13 DEBUG reading talconfig.yaml
2024/03/07 09:11:13 DEBUG substituting config file with environment variable
2024/03/07 09:11:13 DEBUG overriding global controlplane node config for talos-cp-01
2024/03/07 09:11:13 DEBUG start validating talconfig file
2024/03/07 09:11:13 DEBUG validating config file for node talos-cp-01
2024/03/07 09:11:13 DEBUG start generating config file
2024/03/07 09:11:13 DEBUG generating new secret file because secret file is not found
...
```

Exploring talhelper's documentation reveals that the name of the secret file as generated by the cluster template is incorrect; it isn't a filename that's checked by default in the current version. 

```
  -s, --secret-file strings   List of files containing secrets for the cluster (default [talsecret.yaml,talsecret.sops.yaml,talsecret.yml,talsecret.sops.yml])
```

The template tasks should either specify the nonstandard secret file name directly on the command, or generate a file that is one of the expected defaults. Most of the guides suggest using `talsecret.sops.yaml` as the secrets filename.

**Comment by onedr0p** [comment]
This was brought up in Discord, and someone was going to PR the change. I'll get to it today, thanks for reminding me!

**Comment by onedr0p** [comment]
Done in

https://github.com/onedr0p/cluster-template/commit/cadee91bdcbb8810b6db0518f93420807748b227

Thanks!
