### ISSUE TITLE
Fix UDP Buffer Sizes for cloudflared tunnel

### ISSUE THREAD

**Issue by cypr0** [onedr0p/cluster-template#1403]
With the current config I get the following error when starting cloudflared tunnel:

> failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.

To fix this for Debian, modify **cluster-prepare.yaml.j2** as follows:

`sysctl_config:`
`fs.inotify.max_queued_events: 65536`
`fs.inotify.max_user_watches: 524288`
`fs.inotify.max_user_instances: 8192`
`net.core.rmem_max: 2500000`
`net.core.wmem_max: 2500000`

**Comment by onedr0p** [comment]
Fixed in https://github.com/onedr0p/cluster-template/commit/28ae26d3a8d1b3ea79f8552ae420faf93366dda5 thanks for reporting!
