### ISSUE TITLE
Renovate now recommends `config:best-practices`

### ISSUE THREAD

**Issue by Diaoul** [onedr0p/cluster-template#1460]
In their [General Recommendations](https://docs.renovatebot.com/upgrade-best-practices/#general-recommendations), Renovate recommend to extend with the `config:best-practices` preset instead of the `config:recommended` as [currently used](https://github.com/onedr0p/cluster-template/blob/main/.github/renovate.json5#L4).

I've personally tried but it gives me weird errors (maybe that's my own setup IDK), logs just say:

> WARN: Error updating branch: update failure (branch="renovate/pin-dependencies")

Still, I think pinning is a good thing and it should be made the default here. What do you think?

**Comment by onedr0p** [comment]
This is now the 3rd time they changed this 😄

**Comment by onedr0p** [comment]
I'm going to stick with recommended, best practices seems a bit too strict for my tastes.

**Comment by Diaoul** [comment]
Fair enough 🙏
