### ISSUE TITLE
Error: repo coredns not found when bootstrapping Talos cluster

### ISSUE THREAD

**Issue by cypr0** [onedr0p/cluster-template#1490]
The `task talos:bootstrap` command fails, because the repo coredns cannot be found. I fixed this by adding the following lines in `helmfile.yaml` under the `repositories:` section:

```
- name: coredns
  url: https://coredns.github.io/helm
```

**Comment by onedr0p** [comment]
Fixed in https://github.com/onedr0p/cluster-template/pull/1491
