### ISSUE TITLE
Update sops commands in taskfiles to use new `filestatus` arg

### ISSUE THREAD

**Issue by brunnels** [onedr0p/cluster-template#1539]
This should be a lower case `-l`

```
  -L, --files-without-match  print only names of FILEs with no selected lines
  -l, --files-with-matches  print only names of FILEs with selected lines
```

https://github.com/onedr0p/cluster-template/blob/38d00e2197abf549da3c7f39fb618041d1aa9fb3/.taskfiles/Sops/Taskfile.yaml#L21

**Comment by brunnels** [comment]
I'm dumb...  lol.  Encrypt is fine.  The decrypt needed the lower case `-l`.  Can close the PR if you don't want the decrypt.

**Comment by onedr0p** [comment]
As of sops 3.9.0 we can now use the filestatus arg, so this can be improved in other ways, e.g.

```
sops filestatus cluster-secrets.secret.sops.yaml | jq --exit-status '.encrypted'
```
