### ISSUE TITLE
DNS resolution stops working when coredns gets restarted

### ISSUE THREAD

**Issue by DevSecNinja** [onedr0p/cluster-template#1627]
Hey Devin - thanks very much for this awesome template! I ran the template a few years ago with Ubuntu but recently restarted with a simple one node architecture on a Proxmox VM. I noticed a strange issue upon redirecting clients to an auth-url and when `coredns` gets restarted. I documented the issue and the fix on my GitHub fork and thought you might be interested in potentially also adding this change to the template. I'm not 100 % sure on the impact of this change but I'm not super advanced on Kubernetes. I'll keep an eye out for any strange issues that may arise.

https://github.com/DevSecNinja/home/issues/962

**Comment by onedr0p** [comment]
Please open a PR when you have time, if not soon I can get to it too. Thanks for details into this, it's the first I'm hearing about it.

**Comment by DevSecNinja** [comment]
Thanks - will do! Yeah first time for me too. I was able to find 166 repos with Cilium in Kubesearch and 6 repositories with `socketLB.hostNamespaceOnly` to true. Bunch of them have Authentik or Authelia set up so I'm curious if others ran into this as well.

![image](https://github.com/user-attachments/assets/85c14276-4afa-45d8-9eac-aba46b1ecb1b)
