### ISSUE TITLE
`task configure` not working on devcontainer setup

### ISSUE THREAD

**Issue by Stasky745** [onedr0p/cluster-template#1630]
```bash
⬢ [Docker] ❯ task configure
Any conflicting files in the kubernetes directory will be overwritten... continue? [y/N]: y
task: `test -d /workspaces/cluster/.venv` failed
task: Failed to run task "configure": task: precondition not met
```

There's no `.venv` directory in the devcontainer setup. Maybe the `task workstation:venv` command should be used prior too?

**Comment by onedr0p** [comment]
For whatever reason looks like that didn't run, maybe due to you not having this fix.
https://github.com/onedr0p/cluster-template/commit/cabfb1b9ea6568b8814bf19765b98961d9360657

**Comment by DaHofa02** [comment]
oh found out if you open the devcontainer CI this doesn't run maybe he was like me and opened the CI verseion because CI loos like Cl and could mean Cloudflare
