### ISSUE TITLE
Talos upgrade fails as it's using the wrong image

### ISSUE THREAD

**Issue by DevSecNinja** [onedr0p/cluster-template#1634]
Hey!

In this piece of code, it's assumed that the path is `factory.talos.dev/installer` while I am using the secureboot image. Therefore, the path is `factory.talos.dev/installer-secureboot`.

https://github.com/onedr0p/cluster-template/blob/3bacd8ae3d5e521ba3eb29b1c275393f6c3438ae/.taskfiles/talos/Taskfile.yaml#L47

I have set this value correctly in `talosImageURL` on the node. Can we use that value, since the URL should stay the same except for the version tag suffix?

Thanks!

**Comment by DevSecNinja** [comment]
Also per the [upgrade guide](https://www.talos.dev/v1.8/talos-guides/upgrading-talos/), users with a single control-plane node should use `--preserve=true` when running `talosctl --nodes XYZ upgrade`. Any idea if that can be built into the `talosctl` task command? I don't know if we keep track of the amount of control plane nodes though.

**Comment by onedr0p** [comment]
As of 1.8.0 that preserve flag is gone as it always preserves the data now. `talosctl upgrade --help` has no mention of that flag anymore.

The secure boot problem is a little bit of a pain, is there a way to query if security boot is enabled in cluster using kubectl or talosctl?

**Comment by DevSecNinja** [comment]
> As of 1.8.0 that preserve flag is gone as it always preserves the data now. `talosctl upgrade --help` has no mention of that flag anymore.
> 
> The secure boot problem is a little bit of a pain, is there a way to query if secure boot is enabled in cluster using kubectl or talosctl?

Understood! Can you try `talosctl --nodes svlk8s1 get securitystate --output json | jq -r '.spec.secureBoot'`

This returns `true` for me.

**Comment by onedr0p** [comment]
Yep that works for me. I'll work it into the taskfile today.

**Comment by onedr0p** [comment]
Please test this and see if it works: 

https://github.com/onedr0p/cluster-template/commit/cc3551e503e3fb9795e61ddb0eeabbfa46742b58

**Comment by DevSecNinja** [comment]
Thanks - good tip on the dry run! It works!

`task: [talos:upgrade-node] talosctl --nodes svlk8s1 upgrade --image="factory.talos.dev/installer-secureboot/dcac6b92c17d1d8947a0cee5e0e6b6904089aa878c70d66196bb1138dbd05d1a:v1.8.3" --timeout=10m`

Thanks very much!
