### ISSUE TITLE
Unnecessary namespace definition in ingress-nginx internal helmrelease

### ISSUE THREAD

**Issue by brunnels** [onedr0p/cluster-template#1660]
I just saw this while diffing with my old generated code.

https://github.com/onedr0p/cluster-template/blob/5612df757269c8a03de5e0ad1ed1342d58a81084/bootstrap/templates/kubernetes/apps/network/ingress-nginx/internal/helmrelease.yaml.j2#L6

**Comment by onedr0p** [comment]
Fixed in https://github.com/onedr0p/cluster-template/commit/215e3fb3918a2dcbacf2b50dcfc289ce6faecf40
