### ISSUE TITLE
ingress-nginx external HelmRelease has dependsOn defined

### ISSUE THREAD

**Issue by brunnels** [onedr0p/cluster-template#1664]
https://github.com/onedr0p/cluster-template/blob/d62155849bf8b9ee0a1260fe0b25f1fe9dce8a7a/bootstrap/templates/kubernetes/apps/network/ingress-nginx/external/helmrelease.yaml.j2#L23

Just saw this scrubbing my apps for consistency.  Would this be better up in the ingress-nginx/ks.yaml dependsOn?

**Comment by onedr0p** [comment]
I don't think so, there's nothing in the cloudflared ks that needs to be ready other than the helm release.
